version: 2
updates:
    - package-ecosystem: 'npm'
      directories:
          - '/'
          - '/src/plugins/*'
      schedule:
          interval: 'daily'
      commit-message:
          prefix: 'dependabot[bot]'
