version: '3'

services:
    # ==== Application ====

    bot:
        container_name: bot
        restart: unless-stopped
        build:
            context: ./
            dockerfile: ./.docker/app/Dockerfile
        volumes:
            - ./database:/app/database
            - ./logs/:/app/logs
            - ./assets:/app/assets
        env_file:
            - .env
        ports:
            - 4000:4000
        # depends_on:
        #   - database

    # ==== PostgreSQL database ====

    # database:
    #   image: postgres
    #   container_name: database
    #   restart: always
    #   volumes:
    #     - ./data:/var/lib/postgresql:rw
    #   environment:
    #     - POSTGRES_DB=${DATABASE_NAME}
    #     - POSTGRES_USER=${DATABASE_USER}
    #     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    #   ports:
    #     - 5432:5432

    # ==== MySQL database ====

    # database:
    #   image: mysql # or `mariadb`
    #   container_name: database
    #   restart: always
    #   volumes:
    #     - ./data:/var/lib/mysql:rw
    #   environment:
    #     - MYSQL_DATABASE=${DATABASE_NAME}
    #     - MYSQL_USER=${DATABASE_USER}
    #     - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    #     - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    #   ports:
    #     - 3306:3306
