name: Sync with Crowdin

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: true
          auto_approve_imported: true
          import_eq_suggestions: false
          download_sources: true
          push_sources: true
          download_translations: true
          export_only_approved: true
          push_translations: true
          commit_message: 'crowdin[bot]: New translations for %original_file_name% (%language%)'
          localization_branch_name: crowdin/${{ github.ref_name }}
          create_pull_request: true
          pull_request_title: 'crowdin[bot]: New Crowdin updates'
          pull_request_labels: 'crowdin'
          pull_request_base_branch_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
