name: Sync with Crowdin

on:
    push:
        paths:
            - 'src/i18n/*/index.ts'
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    crowdin:
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Sync with Crowdin
              uses: crowdin/github-action@v2
              with:
                  upload_translations: true
                  auto_approve_imported: true
                  download_translations: true
                  export_only_approved: true
                  localization_branch_name: crowdin/${{ github.ref_name }}
                  commit_message: 'crowdin[bot]: New translations from Crowdin'
                  pull_request_title: 'crowdin[bot]: New Crowdin updates'
                  pull_request_labels: 'crowdin'
                  crowdin_branch_name: ${{ github.ref_name }}
              env:
                  GITHUB_TOKEN: ${{ github.token }}
                  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
                  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
