name: Deploy (SSH)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.2.0
        env:
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          envs: PROJECT_PATH
          script: |
            cd "$PROJECT_PATH"
            git pull https://github.com/barthofu/tscord.git main
            docker-compose up -d --build
